xquisite/accounts/urls.py
from django.urls import path
from .views import (
    signup, 
    Profile,
    login,
    logout,
)
from store.views import MyOrders
from medical.views import MyRequests

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup.as_view(), name='signup'),
    path('login/', login.as_view(), name='login'),
    path('logout/', logout.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile/myorders/', MyOrders.as_view(), name='myorders'),
    path('profile/myrequests/', MyRequests.as_view(), name='myrequests'),
]

xquisite/medical/urls.py
from django.urls import path
from .views import (
    MedicalRequestCreate,
    MedicalRequests,
    MedicalRequestUpdate,
)

app_name = 'medical'

urlpatterns = [
    path('', MedicalRequestCreate.as_view(), name='create'),
    path('requests/', MedicalRequests.as_view(), name='list'),
    path('requests/<int:pk>/update', MedicalRequestUpdate.as_view(), name='update'),
]

xquisite/store/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductDetail,
    ProductUpdate,
    ProductCreate,
    ProductDelete,
    OrderCreate,
    Orders,
    OrdersUpdate,
    MyOrders,
)

app_name = 'store'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('new/', ProductCreate.as_view(), name='create'),
    # path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/<int:pk>/update', OrdersUpdate.as_view(), name='update_orders'),
    path('<slug:slug>/', ProductDetail.as_view(), name='detail'),
    path('<slug:slug>/order/', OrderCreate.as_view(), name='order'),
    path('<slug:slug>/update/', ProductUpdate.as_view(), name='update'),
    path('<slug:slug>/delete/', ProductDelete.as_view(), name='delete'),
]

xquisite/xquisite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    home
)

urlpatterns = [
    path("admin/", admin.site.urls, name='home'),
    path('', home.as_view(), name='home'),
    path('', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('medical/', include('medical.urls')),
]

xquisite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %} | Stadinator</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    {% block head %}{% endblock head %}
</head>
<body>
    {% include 'navbar.html' %}
    {% block body %}
    
    {% endblock body %}
    
    {% block scripts %}
        
    {% endblock scripts %}
</body>
</html>

xquisite/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    {% include 'navbar.html' %}
    <h1>{{ title }}</h1>
</body>
</html>

xquisite/templates/navbar.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'styles/navbar.css' %}"/>
</head>
<div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        Stadinator
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>
    
    <div class="nav-links">
      {% if request.user.is_authenticated %}
        <a href="{% url 'store:list' %}">Store</a>
        {% if request.user.is_superuser or request.user.is_staff %}
        <a href="{% url 'medical:list' %}">Medical Requests</a>
        {% else %}
        <a href="{% url 'medical:create' %}">Medical Request</a>
        {% endif %}
        <span style="margin-top: 200px;">
        <a class='profileimg' href="{% url 'accounts:profile' %}">
            <img src='https://ui-avatars.com/api/?name={{request.user.username}}&size=40&bold=true&rounded=true&format=svg&background=random' />
        </a>
        </span>
        {% else %}
          <a href="{% url 'home' %}">Home</a>
          <a href="{% url 'accounts:login' %}">Login</a>
          <a href="{% url 'accounts:signup' %}">Signup</a>
        {% endif %}
    </div>
  </div>