xquisite/store/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductDetail,
    ProductUpdate,
    ProductCreate,
    ProductDelete,
    OrderCreate,
    Orders,
    OrdersUpdate,
    MyOrders,
)

app_name = 'store'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('new/', ProductCreate.as_view(), name='create'),
    # path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/<int:pk>/update', OrdersUpdate.as_view(), name='update_orders'),
    path('<slug:slug>/', ProductDetail.as_view(), name='detail'),
    path('<slug:slug>/order/', OrderCreate.as_view(), name='order'),
    path('<slug:slug>/update/', ProductUpdate.as_view(), name='update'),
    path('<slug:slug>/delete/', ProductDelete.as_view(), name='delete'),
]

xquisite/xquisite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    home
)

urlpatterns = [
    path("admin/", admin.site.urls, name='home'),
    path('', home.as_view(), name='home'),
    path('', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('medical/', include('medical.urls')),
]

xquisite/store/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError
from phonenumber_field.modelfields import PhoneNumberField

def validate_phone(value):
    if len(str(value)) != 12:
        raise ValidationError(
            ("%(value)s is not a valid phone number number"),
            params={"value": value},
        )

class Product(models.Model):
    image = models.ImageField('Product Thumbnail', upload_to='uploads/store', blank=True)
    item_code = models.CharField("Item Code", unique=True, max_length=50)
    name = models.CharField('Product Name', unique=True, max_length=100)
    slug = models.SlugField("Product Slug", unique=True, blank=True)
    description = models.TextField('Description')
    price = models.FloatField("Price")
    in_stock = models.BooleanField("Available in Stock", default=True)
    date_added = models.DateTimeField('Date Added', auto_now_add=True)
    date_updated = models.DateTimeField('Last Updated', auto_now=True)
    
    def __str__(self):
       return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.item_code = self.item_code.upper()
        super(Product, self).save(*args, **kwargs)

class Order(models.Model):
    User = models.ForeignKey("accounts.User", on_delete=models.CASCADE, limit_choices_to={"is_staff": False},)
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, to_field='name', limit_choices_to={"in_stock": True})
    seat = models.CharField("Seat Number", max_length=10)
    phone = PhoneNumberField('Phone Number', help_text='Phone Number alongwith Country Code')
    ordered_at = models.DateTimeField('Ordered at', auto_now_add=True)
    delivered = models.BooleanField('Delivered', default=False)
    
    

xquisite/store/views.py
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Product, Order

class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
    
    model = Product
    fields = '__all__'
    template_name_suffix = '_create'
    
    def get_success_url(self) -> str:
        return reverse_lazy('store:detail', kwargs={'slug': self.object.slug})

class ProductList(LoginRequiredMixin, ListView):
    model = Product
    paginate_by = 25
    
class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    
class ProductUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
    
    model = Product
    fields = '__all__'
    template_name_suffix = '_update'
    
    def get_success_url(self) -> str:
        return reverse_lazy('store:detail', kwargs={'slug': self.object.slug})
    
class ProductDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
    
    model = Product
    success_url = reverse_lazy('store:list')
    template_name_suffix = '_delete'

class OrderCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    def test_func(self) -> bool | None:
        if not (self.request.user.is_superuser or self.request.user.is_staff):
            return True
        else:
            return False
        
    model = Order
    fields = ['seat', 'phone']
    template_name_suffix = '_create'
    success_url = reverse_lazy('store:list')
    
    def form_valid(self, form, **kwargs):
        obj = get_object_or_404(Product, slug=self.kwargs['slug'])
        form.instance.User = self.request.user
        form.instance.Product = obj
        return super().form_valid(form)

# Orders

class Orders(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        else:
            return False
    model = Order

class OrdersUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        else:
            return False
    model = Order
    fields = '__all__'
    template_name_suffix = '_update'
    success_url = reverse_lazy('store:list_orders')
    
class MyOrders(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self) -> bool | None:
        if not (self.request.user.is_superuser or self.request.user.is_staff):
            return True
        else:
            return False
    model = Order
    template_name = 'store/myorders.html'
    
    def get_queryset(self):
        return get_list_or_404(Order, User=self.request.user)
    
    

xquisite/templates/store/myorders.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block title %}My Orders{% endblock title %}


{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}" />
{% endblock head %}
    

{% block body %}
    <h1>My Orders</h1>
    <div class='orders'/>
    <table>
        <tr>
            <th>Product</th>
            <th>Seat</th>
            <th>Phone</th>
            <th>Ordered</th>
            <th>Delivered</th>
        </tr>
        {% for order in object_list %}
            <tr>
                <td><a href="{% url 'store:detail' order.Product.slug %}">{{order.Product}}</a></td>
                <td>{{order.seat}}</td>
                <td><a href="tel:{{order.phone}}">{{order.phone}}</a></td>
                <td>{{order.ordered_at| localtime}}</td>
                <td><input type='checkbox' value='{{order.delivered}}' disabled/></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock body %}
    

xquisite/templates/store/order_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Order Product - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    {% if not request.user.is_staff or not request.user.is_superuser %}
        <h1>Order Product</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Order">
        </form>
    {% else %}
        <p>You cannot order from here.</p>
    {% endif %}
{% endblock body %}
    

xquisite/templates/store/order_list.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block title %}Orders - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}" />
{% endblock head %}
    
{% block body %}
    <h1>View Orders - Store</h1>
    {% comment %} {% if user.is_staff or user.is_superuser %}
    <a href="{% url 'store:create' %}">Add New Product</a>
    <br/>
    {% endif %} {% endcomment %}
    <div class='orders'>
        <table >
            <tr>
                <th>User</th>
                <th>Product</th>
                <th>Seat</th>
                <th>Phone</th>
                <th>Ordered</th>
                <th>Delivered</th>
                <th>Update Status</th>
            </tr>
            {% for order in object_list %}
                {% if not order.delivered %}
                    <tr>
                        <td>{{order.User|urlize}}</td>
                        <td><a href="{% url 'store:detail' order.Product.slug %}">{{order.Product}}</a></td>
                        <td>{{order.seat}}</td>
                        <td><a href="tel:{{order.phone}}">{{order.phone}}</a></td>
                        <td>
                            {{order.ordered_at|localtime}}
                        </td>
                        <td><input type='checkbox' value='{{order.delivered}}' disabled/></td>
                        <td><a href="{% url 'store:update_orders' order.id %}">Update Status</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
{% endblock body %}
    

xquisite/templates/store/order_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update {{object.User}}'s Order - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    <h1>{{object.User}} - {{ object.Product.item_code }}</h1>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock body %}
    

xquisite/templates/store/product_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add Product - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    <h1>Add Product</h1>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock body %}
    

xquisite/templates/store/product_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{object.name}} - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    <h1>{{object.name}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        Do you really wish to delete {{ object.name }}?
        <br/><br/>
        <input type="submit" value="Yes, Delete">
    </form>
{% endblock body %}
    

xquisite/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{object.name}} - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
<div class='product'>
    <h1>{{object.name}}</h1>
    <h3 class="product__price">₹ {{ object.price }}</h3>
    {% if object.image %}
        <img class='product__hero' src="https://stadinator.s3.eu-central-003.backblazeb2.com/static/{{object.image}}" alt="{{object.name}}" fetchpriority='high' loading='eager' />
    {% endif %}
    <p class="product__description">
        {{ object.description }}
    </p>

    {% if request.user.is_staff or request.user.is_superuser %}
        <a class='button-secondary' href="{% url 'store:update' object.slug %}">Update </a>
        <a class='button-primary' href="{% url 'store:delete' object.slug %}">Delete </a>
    {% else %}
        <a class='button-secondary' href="{% url 'store:order' object.slug %}">Order</a>
    {% endif %}
</div>
{% endblock body %}
    

xquisite/templates/store/product_list.html
{% extends 'base.html' %}

{% block title %}Store{% endblock title %}

{% block body %}
    <h1>Store</h1>
    <div class='main'>
    {% if user.is_staff or user.is_superuser %}
    <a class="button-primary" href="{% url 'store:create' %}">Add New Product</a>
    <a class="button-secondary" href="{% url 'store:list_orders' %}">View Orders</a>
    <br/>
    {% endif %}
    <div class="store">
        
        <div class="store__items">
    {% for product in object_list %}
        {% if product.in_stock %}
        <a href="{% url 'store:detail' product.slug %}">
            <div class="store__card"/>
            <img class="store__card__hero" src="https://stadinator.s3.eu-central-003.backblazeb2.com/static/{{product.image}}"/>
            <div class="blog__card__text">
                <h3 >{{product.name}}</h3>
            </div>
        </div>
    </a>
        {% endif %}
    {% endfor %}
</div>
    </div>
    </div>
{% endblock body %}
    

xquisite/templates/store/product_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{object.name}} - Store{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    <h1>{{object.name}}</h1>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock body %}
    