xquisite/medical/urls.py
from django.urls import path
from .views import (
    MedicalRequestCreate,
    MedicalRequests,
    MedicalRequestUpdate,
)

app_name = 'medical'

urlpatterns = [
    path('', MedicalRequestCreate.as_view(), name='create'),
    path('requests/', MedicalRequests.as_view(), name='list'),
    path('requests/<int:pk>/update', MedicalRequestUpdate.as_view(), name='update'),
]

xquisite/store/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductDetail,
    ProductUpdate,
    ProductCreate,
    ProductDelete,
    OrderCreate,
    Orders,
    OrdersUpdate,
    MyOrders,
)

app_name = 'store'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('new/', ProductCreate.as_view(), name='create'),
    # path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/', Orders.as_view(), name='list_orders'),
    path('orders/<int:pk>/update', OrdersUpdate.as_view(), name='update_orders'),
    path('<slug:slug>/', ProductDetail.as_view(), name='detail'),
    path('<slug:slug>/order/', OrderCreate.as_view(), name='order'),
    path('<slug:slug>/update/', ProductUpdate.as_view(), name='update'),
    path('<slug:slug>/delete/', ProductDelete.as_view(), name='delete'),
]

xquisite/xquisite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    home
)

urlpatterns = [
    path("admin/", admin.site.urls, name='home'),
    path('', home.as_view(), name='home'),
    path('', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('medical/', include('medical.urls')),
]

xquisite/medical/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from store.models import validate_phone

class MedicalRequest(models.Model):
    User = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, limit_choices_to={'is_staff': False})
    description = models.TextField('Medical Emergency Despription')
    phone = PhoneNumberField("Phone Number", help_text='Phone Number alongwith Country Code')
    seat = models.CharField('Seat Number', max_length=50)
    is_resolved = models.BooleanField("Resolved", default=False)
    requested_at = models.DateTimeField("Requested at", auto_now_add=True)

xquisite/medical/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import MedicalRequest

class MedicalRequestCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    def test_func(self) -> bool | None:
        if not (self.request.user.is_superuser or self.request.user.is_staff):
            return True
        else:
            return False
        
    model = MedicalRequest
    fields = ['description', 'seat', 'phone']
    template_name_suffix = '_create'
    success_url = reverse_lazy('store:list')
    
    def form_valid(self, form, **kwargs):
        form.instance.User = self.request.user
        return super().form_valid(form)

class MedicalRequests(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        else:
            return False
    model = MedicalRequest

class MedicalRequestUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self) -> bool | None:
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        else:
            return False
    model = MedicalRequest
    fields = '__all__'
    # fields = ['seat', 'requested_at', 'is_resolved']
    readonly_fields = ['User']
    template_name_suffix = '_update'
    success_url = reverse_lazy('medical:list')

class MyRequests(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self) -> bool | None:
        if not (self.request.user.is_superuser or self.request.user.is_staff):
            return True
        else:
            return False
    model = MedicalRequest
    template_name = 'medical/myrequests.html'
    
    def get_queryset(self):
        return get_list_or_404(MedicalRequest, User=self.request.user)

xquisite/templates/medical/medicalrequest_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Medical Request{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    {% if not request.user.is_staff or not request.user.is_superuser %}
        <h1>Order Product</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Request">
        </form>
    {% else %}
        <p>You cannot request medical help.</p>
    {% endif %}
{% endblock body %}
    

xquisite/templates/medical/medicalrequest_list.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block title %}Medical Requests{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}" />
{% endblock head %}
    
{% block body %}
    <h1>Medical Requests</h1>
    {% comment %} {% if user.is_staff or user.is_superuser %}
    <a href="{% url 'store:create' %}">Add New Product</a>
    <br/>
    {% endif %} {% endcomment %}
    <div class='orders'>
    <table>
        <tr>
            <th>User</th>
            <th>Seat</th>
            <th>Phone</th>
            <th>Requested at</th>
            <th>Resolved</th>
            <th>Update Status</th>
        </tr>
        {% for request in object_list %}
            {% if not request.is_resolved %}
                <tr>
                    <td>{{request.User|urlize}}</td>
                    <td>{{request.seat}}</td>
                    <td><a href="tel:{{request.phone}}">{{request.phone}}</a></td>
                    <td>
                        {{request.requested_at|localtime}}
                    </td>
                    <td><input type='checkbox' value='{{request.resolved}}' disabled/></td>
                    <td><a href="{% url 'medical:update' request.id %}">Update Status</a></td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</div>
{% endblock body %}
    

xquisite/templates/medical/medicalrequest_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update {{object.User}}'s Medical Request{% endblock title %}

{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}"/>
{% endblock head %}

{% block body %}
    <h1>{{object.User}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock body %}
    

xquisite/templates/medical/myrequests.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block title %}My Medical Requests{% endblock title %}


{% block head %}
    <link rel='stylesheet' href="{% static 'styles/store.css' %}" />
{% endblock head %}
    

{% block body %}
    <h1>My Medical Requests</h1>
    <table class='orders'>
        <tr>
            <th>Seat</th>
            <th>Phone</th>
            <th>Requested at</th>
            <th>Resolved</th>
        </tr>
        {% for request in object_list %}
            <tr>
                <td>{{request.seat}}</td>
                <td><a href="tel:{{request.phone}}">{{request.phone}}</a></td>
                <td>{{request.requested_at| localtime}}</td>
                <td><input type='checkbox' value='{{request.is_resolved}}' disabled/></td>
            </tr>
        {% endfor %}
    </table>
{% endblock body %}
    